-- Dates
INSERT INTO dim_date (date_id, annee, mois, trimestre) VALUES
('2025-01-01', 2025, 1, 1);

-- Activity types (postes carbone)
INSERT INTO dim_activity_type (activity_type_id, ensemble, poste, sous_poste, libelle, unite_reference) values
(1, 'Fonctionnement', 'Bâtiment', 'Surface plancher', 'Surface plancher du cinéma', 'm2'),
(2, 'Fonctionnement', 'Bâtiment', 'Surface rénovation', 'Surface rénové du cinéma', 'm2'),
(3, 'Fonctionnement', 'Bâtiment', 'Surface supplémentaire', 'Surface supplémentaire du cinéma', 'm2'),
(4, 'Fonctionnement', 'Bâtiment', 'Coût de rénovation', 'Coût de rénovation', '€'),
(5, 'Fonctionnement', 'Bâtiment', 'Surface totale', 'Surface totale du bâtiment (cinéma inclus)', 'm2'),
(6, 'Fonctionnement', 'Bâtiment', 'Parking', 'Nombre de parking', 'places'),
(7, 'Fonctionnement', 'Équipe', 'Rythme de travail', 'Repas consommés', 'repas'),
(8, 'Fonctionnement', 'Équipe', 'Rythme de travail', 'Distance domicile-travail', 'km'),
(9, 'Fonctionnement', 'Déplacements professionnels', 'RER & Trasilien', 'Déplacements professionnels', 'km'),
(10, 'Fonctionnement', 'Déplacements professionnels', 'Métro/Tram', 'Déplacements professionnels', 'km'),
(11, 'Fonctionnement', 'Déplacements professionnels', 'Vélo électrique', 'Déplacements professionnels', 'km'),
(12, 'Fonctionnement', 'Déplacements professionnels', 'Vélo classique', 'Déplacements professionnels', 'km'),
(13, 'Fonctionnement', 'Déplacements professionnels', 'Marche', 'Déplacements professionnels', 'km'),
(14, 'Fonctionnement', 'Déplacements professionnels', 'Voiture diesel', 'Déplacements professionnels', 'km'),
(15, 'Fonctionnement', 'Déplacements professionnels', 'Voiture essence', 'Déplacements professionnels', 'km'),
(16, 'Fonctionnement', 'Déplacements professionnels', 'Voiture hybride', 'Déplacements professionnels', 'km'),
(17, 'Fonctionnement', 'Déplacements professionnels', 'Voiture électrique', 'Déplacements professionnels', 'km'),
(18, 'Fonctionnement', 'Déplacements professionnels', 'Moto', 'Déplacements professionnels', 'km'),
(19, 'Fonctionnement', 'Déplacements professionnels', 'Moto', 'Déplacements professionnels', 'km'),
(20, 'Fonctionnement', 'Déplacements professionnels', 'Scooter', 'Déplacements professionnels', 'km'),
(21, 'Fonctionnement', 'Déplacements professionnels', 'Trotinette électrique', 'Déplacements professionnels', 'km'),
(22, 'Fonctionnement', 'Énergie', 'Électricité', 'Consommation électrique', 'kWh'),
(23, 'Fonctionnement', 'Énergie', 'Gas', 'Consommation gas', 'm3'),
(24, 'Fonctionnement', 'Énergie', 'Fuel', 'Consommation fuel', 'L'),
(25, 'Fonctionnement', 'Énergie', 'Réseaux urbains chaleur', 'Consommation réseau chaleur', 'kWh'),
(26, 'Fonctionnement', 'Énergie', 'Réseaux urbains chaleurfroid', 'Consommation réseau froid', 'kWh'),
(27, 'Fonctionnement', 'Énergie', 'Bois granulés', 'Consommation bois granulés', 'kWh'),
(28, 'Fonctionnement', 'Énergie', 'Groupes électrogène', 'Consommation  électrogène', 'u'),
(29, 'Fonctionnement', 'Énergie', 'Climatisation', 'Consommation climatisation', 'kWh'),
(30, 'Fonctionnement', 'Énergie', 'Diesel', 'Consommation  diesel', 'L'),
(31, 'Fonctionnement', 'Activités de bureau', 'Fournitures', 'Fournitures', '€'),
(32, 'Fonctionnement', 'Activités de bureau', 'Fournitures', 'Services', '€'),
(33, 'Fonctionnement', 'Activités de bureau', 'Ordinateurs fixes', 'Achetés', 'u'),
(34, 'Fonctionnement', 'Activités de bureau', 'Ordinateurs fixes', 'Loués', 'u'),
(35, 'Fonctionnement', 'Activités de bureau', 'Ordinateurs portables', 'Achetés', 'u'),
(36, 'Fonctionnement', 'Activités de bureau', 'Ordinateurs portables', 'Loués', 'u'),
(37, 'Mobilité spectateurs', 'Déplacements', 'RER & Transilien', 'Déplacements spectateurs', 'km'),
(38, 'Mobilité spectateurs', 'Déplacements', 'Métro/Tram', 'Déplacements spectateurs', 'km'),
(39, 'Mobilité spectateurs', 'Déplacements', 'Bus', 'Déplacements spectateurs', 'km'),
(40, 'Mobilité spectateurs', 'Déplacements', 'Vélo électrique', 'Déplacements spectateurs', 'km'),
(41, 'Mobilité spectateurs', 'Déplacements', 'Vélo classique', 'Déplacements spectateurs', 'km'),
(42, 'Mobilité spectateurs', 'Déplacements', 'Vélo électrique', 'Déplacements spectateurs', 'km'),
(43, 'Mobilité spectateurs', 'Déplacements', 'Marche', 'Déplacements spectateurs', 'km'),
(44, 'Mobilité spectateurs', 'Déplacements', 'Voiture diesel', 'Déplacements spectateurs', 'km'),
(45, 'Mobilité spectateurs', 'Déplacements', 'Voiture hybride', 'Déplacements spectateurs', 'km'),
(46, 'Mobilité spectateurs', 'Déplacements', 'Voiture électrique', 'Déplacements spectateurs', 'km'),
(47, 'Mobilité spectateurs', 'Déplacements', 'Moto', 'Déplacements spectateurs', 'km'),
(48, 'Mobilité spectateurs', 'Déplacements', 'Scooter', 'Déplacements spectateurs', 'km'),
(49, 'Mobilité spectateurs', 'Déplacements', 'Trotinette électrique', 'Déplacements spectateurs', 'km'),
(50, 'Tournées avant-première', 'Equipes reçues', 'NULL', 'NULL', 'u'),
(51, 'Tournées avant-première', 'Déplacement', 'NULL', 'NULL', 'u'),
(52, 'Tournées avant-première', 'Déplacement', 'RER & Transilien', 'Déplacements tournées', 'km'),
(53, 'Tournées avant-première', 'Déplacement', 'Métro/Tram', 'Déplacements tournées', 'km'),
(54, 'Tournées avant-première', 'Déplacement', 'Bus', 'Déplacements tournées', 'km'),
(55, 'Tournées avant-première', 'Déplacement', 'Vélo électrique', 'Déplacements tournées', 'km'),
(56, 'Tournées avant-première', 'Déplacement', 'Vélo classique', 'Déplacements tournées', 'km'),
(57, 'Tournées avant-première', 'Déplacement', 'Vélo électrique', 'Déplacements tournées', 'km'),
(58, 'Tournées avant-première', 'Déplacement', 'Marche', 'Déplacements tournées', 'km'),
(59, 'Tournées avant-première', 'Déplacement', 'Voiture diesel', 'Déplacements tournées', 'km'),
(60, 'Tournées avant-première', 'Déplacement', 'Voiture hybride', 'Déplacements tournées', 'km'),
(61, 'Tournées avant-première', 'Déplacement', 'Voiture électrique', 'Déplacements tournées', 'km'),
(62, 'Tournées avant-première', 'Déplacement', 'Moto', 'Déplacements tournées', 'km'),
(63, 'Tournées avant-première', 'Déplacement', 'Scooter', 'Déplacements tournées', 'km'),
(64, 'Tournées avant-première', 'Déplacement', 'Trotinette électrique', 'Déplacements tournées', 'km'),
(65, 'Salles et cabines', 'Matériell technique', 'Salle', 'Nombre de salles' 'u'),
(66, 'Salles et cabines', 'Matériell technique', 'Projecteur', 'Nombre de projecteurs' 'u'),
(67, 'Salles et cabines', 'Matériell technique', 'Écran', 'Nombre de lecran', 'u'),
(68, 'Salles et cabines', 'Matériell technique', 'Fauteuil', 'Nombre de fauteuil', 'u'),
(69, 'Salles et cabines', 'Matériell technique', 'Système de son', 'Système de son', 'u'),
(70, 'Salles et cabines', 'Matériell technique', 'Stockage de films', 'Serveur', 'Go'),
(71, 'Salles et cabines', 'Matériell technique', 'Stockage de films', 'Baies de disques', 'u'),
(72, 'Salles et cabines', 'Matériell technique', 'Films dématérisalisé', 'Films reçus en dématérialisé', 'Go'),
(73, 'Salles et cabines', 'Matériell technique', 'Stockage de films', 'Données stockées dans le cloud', 'Go'),
(74, 'Salles et cabines', 'Matériell technique', 'Stockage de films', 'Données stockées dans les disques dures', 'Go'),
(75, 'Salles et cabines', 'Autre matériel', 'Lunettes 3D', 'NULL', 'u'),
(76, 'Confiseries et boissons', 'Achats', 'Part','Nombre de part achetés par les spectateurs', 'g'),
(77, 'Confiseries et boissons', 'Electroménager', 'Réfrigérateurs', 'Achetés', 'u'),
(78, 'Confiseries et boissons', 'Electroménager', 'Réfrigérateurs', 'Loués', 'u'),
(79, 'Déchets', 'Déchets ordinaires', 'Ordures ménagères', 'Nombre des bennes', 'u'),
(80, 'Déchets', 'Déchets ordinaires', 'Ordures ménagères', 'Taille des bennes', 'u'),
(81, 'Déchets', 'Déchets ordinaires', 'Ordures ménagères', 'Fréquence de ramassage', 'fois/semaine'),
(82, 'Déchets', 'Déchets exeptionnels', 'Lampes Xenons', 'Nombre de lampes jettées', 'u'),
(83, 'Déchets', 'Déchets exeptionnels', 'Matériel technique', 'Poids de matériel jetté', 'kg'),
(84, 'Billetterie et communication', 'Matériel distributeurs', 'Affiches 120x160', 'NULL', 'u'),
(85, 'Billetterie et communication', 'Matériel distributeurs', 'Affiches 40x60', 'NULL', 'u'),
(86, 'Billetterie et communication', 'Matériel cinéma', 'Programme', 'NULL', 'u'),
(87, 'Billetterie et communication', 'Matériel cinéma', 'Affiches', 'NULL', 'u'),
(88, 'Billetterie et communication', 'Matériel cinéma', 'Flyers', 'NULL', 'u'),
(89, 'Billetterie et communication', 'Communication digitale', 'Newsletters', 'Nombre de newsletters envoyées', 'u'),
(90, 'Billetterie et communication', 'Communication digitale', 'Caissons', 'Nombre de caissons daffichage dynamique', 'u'),
(91, 'Billetterie et communication', 'Communication digitale', 'Ecrans TV', 'Nombre decran se trouve dans lespaces de circulation', 'u'),
(92, 'Billetterie et communication', 'Communication digitale', 'LED', 'Surface daffichage extérieur', 'm2'),
(93, 'Billetterie et communication', 'Caisses et bornes', 'Caisse LS', 'Nombre de caisses libre-services', 'u'),
(94, 'Billetterie et communication', 'Caisses et bornes', 'Caisse classique', 'Nombre de caisses classiques', 'u');

-- Emission factors
INSERT INTO dim_emission_factor (ef_id, activity_type_id, emission_factor, unite_ef) VALUES
(20730, 1, 825, 'kgCO2e'),
(20730, 2, 825, 'kgCO2e'),
(20730, 3, 825, 'kgCO2e'),
(43340, 4, 245, 'kgCO2e'),
(20730, 5, 825, 'kgCO2e'),
(26008, 6, 92, 'kgCO2e'),
(20682, 7, 204, 'kgCO2e'),
(24155, 9, 698, 'kgCO2e'),
(24155, 10, 698, 'kgCO2e'),
(24191, 11, 398, 'kgCO2e'),
(24191, 12, 398, 'kgCO2e'),
(24170, 13, 1474, 'kgCO2e'),
(24184, 14, 6317, 'kgCO2e'),
(24184, 15, 6317, 'kgCO2e'),
(24184, 16, 6317, 'kgCO2e'),
(24184, 17, 6317, 'kgCO2e'),
(24191, 18, 398, 'kgCO2e'),
(24191, 19, 398, 'kgCO2e'),
(24191, 20, 398, 'kgCO2e'),
(24191, 21, 398, 'kgCO2e'),
(22, 0.056, 'kgCO2e'),
(15591, 23, 0.056, 'kgCO2e'),
(24, 0.056, 'kgCO2e'),
(25, 0.056, 'kgCO2e'),
(26, 0.056, 'kgCO2e'),
(27, 0.056, 'kgCO2e'),
(28, 0.056, 'kgCO2e'),
(29, 0.056, 'kgCO2e'),
(30, 0.056, 'kgCO2e'),
(31, 0.056, 'kgCO2e'),
(32, 0.056, 'kgCO2e'),
(33, 0.056, 'kgCO2e'),
(34, 0.056, 'kgCO2e'),
(35, 0.056, 'kgCO2e'),
(36, 0.056, 'kgCO2e'),
(37, 0.056, 'kgCO2e'),
(38, 0.056, 'kgCO2e'),
(39, 0.056, 'kgCO2e'),
(40, 0.056, 'kgCO2e'),
(41, 0.056, 'kgCO2e'),
(42, 0.056, 'kgCO2e'),
(43, 0.056, 'kgCO2e'),
(44, 0.056, 'kgCO2e'),
(45, 0.056, 'kgCO2e'),
(46, 0.056, 'kgCO2e'),
(47, 0.056, 'kgCO2e'),
(48, 0.056, 'kgCO2e'),
(49, 0.056, 'kgCO2e'),
(50, 0.056, 'kgCO2e'),
(51, 0.056, 'kgCO2e'),
(52, 0.056, 'kgCO2e'),
(53, 0.056, 'kgCO2e'),
(54, 0.056, 'kgCO2e'),
(55, 0.056, 'kgCO2e'),
(56, 0.056, 'kgCO2e'),
(57, 0.056, 'kgCO2e'),
(58, 0.056, 'kgCO2e'),
(59, 0.056, 'kgCO2e'),
(60, 0.056, 'kgCO2e'),
(61, 0.056, 'kgCO2e'),
(62, 0.056, 'kgCO2e'),
(63, 0.056, 'kgCO2e'),
(64, 0.056, 'kgCO2e'),
(65, 0.056, 'kgCO2e'),
(66, 0.056, 'kgCO2e'),
(67, 0.056, 'kgCO2e'),
(68, 0.056, 'kgCO2e'),
(69, 0.056, 'kgCO2e'),
(70, 0.056, 'kgCO2e'),
(71, 0.056, 'kgCO2e'),
(72, 0.056, 'kgCO2e'),
(73, 0.056, 'kgCO2e'),
(74, 0.056, 'kgCO2e'),
(75, 0.056, 'kgCO2e'),
(76, 0.056, 'kgCO2e'),
(77, 0.056, 'kgCO2e'),
(78, 0.056, 'kgCO2e'),
(79, 0.056, 'kgCO2e'),
(80, 0.056, 'kgCO2e'),
(81, 0.056, 'kgCO2e'),
(82, 0.056, 'kgCO2e'),
(83, 0.056, 'kgCO2e'),
(84, 0.056, 'kgCO2e'),
(85, 0.056, 'kgCO2e'),
(86, 0.056, 'kgCO2e'),
(87, 0.056, 'kgCO2e'),
(88, 0.056, 'kgCO2e'),
(89, 0.056, 'kgCO2e'),
(90, 0.056, 'kgCO2e'),
(91, 0.056, 'kgCO2e'),
(92, 0.056, 'kgCO2e'),
(93, 0.056, 'kgCO2e'),
(94, 0.056, 'kgCO2e');


-- Cinema
INSERT INTO dim_cinema (
  cinema_id, nom_cinema, departement,
  nb_entrees, nb_jours_ouverture, nb_films_programmes,
  annee_construction, presence_clim, vente_confiserie, enquete_mobilite
) VALUES (
  1, 'Cinéma Lumière', '75-Paris', 180000, 320, 1200,
  1998, true, true, true
);
